In [20]:
%run DMD_functions-f.ipynb 
%run Hemati_DMD_functions.ipynb

[0 0 0 3 4 5 0 0 0 0]
[[0.89]
 [0.31]
 [0.34]]
[0.89 0.31 0.34 0.   0.   0.   0.   0.   0.   0.  ]
16
0
8
(18, 18)
8
[[-0.58  0.45  0.44 -0.16  0.32  0.03  0.09  0.05  0.36 -0.05  0.    0.
   0.    0.    0.    0.    0.    0.  ]
 [-0.54 -0.57 -0.45  0.11  0.05  0.16  0.1   0.14  0.3  -0.12  0.    0.
   0.    0.    0.    0.    0.    0.  ]
 [-0.61  0.08 -0.02  0.06 -0.36 -0.18 -0.18 -0.17 -0.61  0.16  0.    0.
   0.    0.    0.    0.    0.    0.  ]
 [ 0.   -0.68  0.66 -0.18  0.12 -0.14 -0.04 -0.11 -0.1   0.09  0.    0.
   0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.42  0.57 -0.5   0.35  0.07  0.26  0.07 -0.22  0.    0.
   0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.77  0.48 -0.3  -0.05 -0.21 -0.    0.18  0.    0.
   0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.52  0.48 -0.07  0.31 -0.58 -0.26  0.    0.
   0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.69 -0.1  -0.54  0.1   0.46  0.    0.
   0.    0.    0.    0.    0.    0

In [21]:
A = np.random.rand(10,10)
x = np.random.rand(10).reshape(-1,1)
X=np.empty((10, 5))
Y=np.empty_like(X)
for i in range(5):
    X[:,i] = x.reshape(-1)
    x = A@x
    Y[:,i]=x.reshape(-1)

In [22]:
Y@np.linalg.pinv(X) -A

array([[ 0.3 ,  0.22,  0.23, -0.27, -0.04, -0.24, -0.33,  0.13,  0.14,
        -0.35],
       [-0.27, -0.05,  0.2 ,  0.27,  0.03, -0.04, -0.11, -0.13,  0.42,
        -0.31],
       [ 0.25, -0.15, -0.1 ,  0.07,  0.13,  0.04, -0.35,  0.23, -0.13,
        -0.25],
       [-0.07, -0.27, -0.05,  0.39,  0.32,  0.16, -0.45,  0.26, -0.23,
        -0.34],
       [ 0.18, -0.17, -0.25,  0.17, -0.09,  0.06, -0.  , -0.05,  0.32,
        -0.22],
       [-0.11,  0.03, -0.13,  0.41,  0.2 ,  0.09, -0.35,  0.22, -0.02,
        -0.6 ],
       [ 0.52,  0.17, -0.2 , -0.3 , -0.15, -0.11, -0.09,  0.15,  0.01,
        -0.18],
       [-0.1 , -0.04,  0.14,  0.19,  0.1 , -0.03, -0.25,  0.04,  0.16,
        -0.32],
       [-0.07,  0.27,  0.52, -0.22, -0.05, -0.29, -0.19, -0.07,  0.31,
        -0.22],
       [-0.31,  0.28, -0.06,  0.21,  0.27,  0.11, -0.15,  0.27, -0.52,
        -0.22]])

In [23]:
Z, Lambda = DMD_exact(X, Y)

In [24]:
for i in range(Z.shape[1]):
    rez=A@Z[:,i]-Lambda[i]*Z[:,i]
    print(np.linalg.norm(rez))

0.0001599765733946056
0.19241844762182972
0.19241844762182972
4.051066756249886
2.173039317901801


In [25]:
for i in range(Z.shape[1]):
    A_pom=Y@np.linalg.pinv(X)
    rez=A_pom@Z[:,i]-Lambda[i]*Z[:,i]
    print(np.linalg.norm(rez))

3.464749749289369e-14
1.40675902832347e-12
1.40675902832347e-12
2.673523312404198e-11
1.3927806146636373e-11


In [26]:
Z_nije_ex, Lambda_nije_ex, r_nije_ex = GEDMD(X, Y)
print(r_nije_ex)

[0.   0.17 0.17 0.24 0.25]
