# JEDNOSTAVNA PROVJERA fDMD

In [1]:
%run fDMD_functions.ipynb

In [2]:
A=np.random.rand(4,4); A=A/np.linalg.norm(A)
x=np.ones((4,1))
y=A@x
Xevi = np.bmat([[np.copy(x)],[np.copy(y)]])
x=y
for i in range(30):
    y=A@x
    Xevi = np.bmat([Xevi, np.bmat([[np.copy(x)],[np.copy(y)]])])
    x=y

np.set_printoptions(2)
Xevi

matrix([[1.00e+00, 4.08e-01, 2.67e-01, 1.95e-01, 1.43e-01, 1.05e-01,
         7.67e-02, 5.61e-02, 4.10e-02, 3.00e-02, 2.19e-02, 1.60e-02,
         1.17e-02, 8.58e-03, 6.28e-03, 4.59e-03, 3.36e-03, 2.45e-03,
         1.80e-03, 1.31e-03, 9.60e-04, 7.02e-04, 5.13e-04, 3.76e-04,
         2.75e-04, 2.01e-04, 1.47e-04, 1.07e-04, 7.85e-05, 5.74e-05,
         4.20e-05],
        [1.00e+00, 7.74e-01, 5.42e-01, 3.93e-01, 2.87e-01, 2.10e-01,
         1.54e-01, 1.12e-01, 8.21e-02, 6.01e-02, 4.39e-02, 3.21e-02,
         2.35e-02, 1.72e-02, 1.26e-02, 9.19e-03, 6.72e-03, 4.91e-03,
         3.59e-03, 2.63e-03, 1.92e-03, 1.41e-03, 1.03e-03, 7.52e-04,
         5.50e-04, 4.02e-04, 2.94e-04, 2.15e-04, 1.57e-04, 1.15e-04,
         8.41e-05],
        [1.00e+00, 9.62e-01, 7.58e-01, 5.63e-01, 4.12e-01, 3.01e-01,
         2.20e-01, 1.61e-01, 1.18e-01, 8.62e-02, 6.30e-02, 4.61e-02,
         3.37e-02, 2.47e-02, 1.80e-02, 1.32e-02, 9.64e-03, 7.05e-03,
         5.16e-03, 3.77e-03, 2.76e-03, 2.02e-03, 1.47e-03, 1.08

In [3]:
np.linalg.eig(A)

(array([ 0.73+0.j , -0.17+0.j ,  0.1 +0.1j,  0.1 -0.1j]),
 array([[-0.2 +0.j  , -0.1 +0.j  ,  0.38-0.16j,  0.38+0.16j],
        [-0.41+0.j  ,  0.54+0.j  , -0.1 -0.21j, -0.1 +0.21j],
        [-0.58+0.j  ,  0.53+0.j  , -0.05+0.55j, -0.05-0.55j],
        [-0.67+0.j  , -0.65+0.j  , -0.69+0.j  , -0.69-0.j  ]]))

In [4]:
GEDMD(Xevi[:4,:20], Xevi[4:,:20]) #iste sv. vrijednosti

(matrix([[ 0.2 +0.j  , -0.41-0.03j, -0.41+0.03j, -0.1 +0.j  ],
         [ 0.41+0.j  , -0.01+0.24j, -0.01-0.24j,  0.54+0.j  ],
         [ 0.58+0.j  ,  0.29-0.47j,  0.29+0.47j,  0.53+0.j  ],
         [ 0.67+0.j  ,  0.61+0.31j,  0.61-0.31j, -0.65+0.j  ]]),
 array([ 0.73+0.j ,  0.1 +0.1j,  0.1 -0.1j, -0.17+0.j ]),
 array([0.48, 0.96, 0.65, 0.35]))

In [5]:
Z, Lambda, r, Q, L = fGEDMDQ_multiple_trajectories(Xevi[:4,:20], Xevi[4:,:20])
Lambda #iste sv. vrij.
r

array([0.37, 0.44, 0.39, 0.62])

In [6]:
Z, Lambda, r, Q, L = fDMD_added_snap(Xevi[:,20], Q, L)

In [7]:
r

array([0.37, 0.44, 0.39, 0.62])

In [8]:
m=4
indices = np.array([i for i in range(4)]); times=[i for i in range(31)]
reconstructed=DMD_reconstruction(Xevi[:m,:], Z, indices, Lambda, times)

In [9]:
reconstructed-Xevi[:m,:]

matrix([[-1.78e-15,  3.89e-16,  3.33e-16,  3.89e-16,  3.33e-16,
          3.05e-16,  2.64e-16,  2.15e-16,  1.87e-16,  1.49e-16,
          1.21e-16,  1.01e-16,  7.81e-17,  6.07e-17,  4.51e-17,
          3.56e-17,  2.78e-17,  2.13e-17,  1.67e-17,  1.28e-17,
          1.01e-17,  7.48e-18,  5.64e-18,  4.45e-18,  3.36e-18,
          2.57e-18,  1.98e-18,  1.48e-18,  1.12e-18,  8.61e-19,
          6.37e-19],
        [-3.33e-16,  0.00e+00,  4.44e-16,  5.55e-16,  6.11e-16,
          5.27e-16,  4.44e-16,  3.47e-16,  3.33e-16,  2.71e-16,
          2.29e-16,  1.73e-16,  1.35e-16,  1.08e-16,  8.50e-17,
          6.59e-17,  5.03e-17,  3.99e-17,  3.12e-17,  2.43e-17,
          1.91e-17,  1.45e-17,  1.11e-17,  8.24e-18,  6.51e-18,
          4.88e-18,  3.74e-18,  2.82e-18,  2.14e-18,  1.64e-18,
          1.22e-18],
        [-4.44e-16, -2.22e-16,  1.11e-16,  3.33e-16,  3.33e-16,
          5.00e-16,  3.89e-16,  3.89e-16,  3.33e-16,  2.78e-16,
          2.36e-16,  2.01e-16,  1.60e-16,  1.35e-16,  1.04e-16